Repository bxcowo/PracticaCalificada3_Grupo5, pull requests merged in 2025-06, with the labels that each got.

#25 Feature/llenado modulos: filling terraform files in each defined module
  iac/compute/main.tf
  iac/compute/outputs.tf
  iac/compute/variables.tf
  iac/logging/main.tf
  iac/logging/outputs.tf
  iac/logging/variables.tf
  iac/monitoring/main.tf
  iac/monitoring/outputs.tf
  iac/monitoring/variables.tf
  iac/network/main.tf
  iac/network/outputs.tf
  iac/network/variables.tf
  iac/security/main.tf
  iac/security/outputs.tf
  iac/security/variables.tf
  iac/storage/main.tf
  iac/storage/outputs.tf
  iac/storage/variables.tf
Labels: medium priority

#29 docs(README): Update README according to sprint 1 specifications.
  README.md
Labels: high priority

#34 Feature/write markdown
  docs/compute.md
  docs/logging.md
  docs/monitoring.md
  docs/network.md
  docs/security.md
  docs/storage.md
  scripts/template.md
  scripts/terraform_docs.py
Labels: medium priority

#37 Feature/create index
  docs/index.md
  scripts/templates/template.md
  scripts/templates/template_index.md
  scripts/terraform_docs.py
Labels: medium priority

#38 docs(readme): update sprint 2 achievements
  README.md
Labels: low priority

#42 update(readme): add link to sprint2 video
  README.md
Labels: low priority
